### PR TITLE
Fix invalid read in hyp1f1 tests

### LINKED ISSUE #137: Invalid read/write in hyp1f1 tests
Valgrind reports invalid read and write in hyp1f1 tests. See below for a sample output.

<details>

```
$ valgrind ./main_test_suite
==20193== Memcheck, a memory error detector
==20193== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==20193== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==20193== Command: ./main_test_suite
==20193== 
Running 3 test cases...
==20193== Invalid read of size 8
==20193==    at 0x133F80: assignCoeff (AssignEvaluator.h:631)
==20193==    by 0x133F80: assignCoeffByOuterInner (AssignEvaluator.h:645)
==20193==    by 0x133F80: run (AssignEvaluator.h:326)
==20193==    by 0x133F80: call_dense_assignment_loop<Eigen::Matrix<double, -1, -1>, Eigen::Ref<Eigen::Array<double, 1, -1, 1, 1, -1> >, Eigen::internal::assign_op<double, double> > (AssignEvaluator.h:741)
==20193==    by 0x133F80: run (AssignEvaluator.h:879)
==20193==    by 0x133F80: call_assignment_no_alias<Eigen::Matrix<double, -1, -1>, Eigen::Ref<Eigen::Array<double, 1, -1, 1, 1, -1> >, Eigen::internal::assign_op<double, double> > (AssignEvaluator.h:836)
==20193==    by 0x133F80: _set_noalias<Eigen::Ref<Eigen::Array<double, 1, -1, 1, 1, -1> > > (PlainObjectBase.h:728)
==20193==    by 0x133F80: PlainObjectBase<Eigen::Ref<Eigen::Array<double, 1, -1, 1, 1, -1> > > (PlainObjectBase.h:537)
==20193==    by 0x133F80: Matrix<Eigen::Ref<Eigen::Array<double, 1, -1, 1, 1, -1> > > (Matrix.h:379)
==20193==    by 0x133F80: void rascal::test_gradients<rascal::Hyp1f1GradientProvider, rascal::GradientTestFixture>(rascal::Hyp1f1GradientProvider, rascal::GradientTestFixture) (test_math.hh:334)
==20193==    by 0x11D112: rascal::MathHyp1f1Tests::hyp1f1_gradient_test::test_method() (test_math_hyp1f1.cc:141)
==20193==    by 0x11D71C: rascal::MathHyp1f1Tests::hyp1f1_gradient_test_invoker() (test_math_hyp1f1.cc:131)
==20193==    by 0x4E872CD: boost::detail::function::function_obj_invoker0<boost::detail::forward, int>::invoke(boost::detail::function::function_buffer&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E8677C: boost::execution_monitor::catch_signals(boost::function<int ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E86860: boost::execution_monitor::execute(boost::function<int ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E86FDC: boost::execution_monitor::vexecute(boost::function<void ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4EB58D0: boost::unit_test::unit_test_monitor_t::execute_and_translate(boost::function<void ()> const&, unsigned int) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E91C6A: boost::unit_test::framework::state::execute_test_tree(unsigned long, unsigned int, boost::unit_test::framework::state::random_generator_helper const*) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E91E50: boost::unit_test::framework::state::execute_test_tree(unsigned long, unsigned int, boost::unit_test::framework::state::random_generator_helper const*) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E91E50: boost::unit_test::framework::state::execute_test_tree(unsigned long, unsigned int, boost::unit_test::framework::state::random_generator_helper const*) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E8ACC7: boost::unit_test::framework::run(unsigned long, bool) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==  Address 0x606c190 is 0 bytes inside a block of size 96 free'd
==20193==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==20193==    by 0x129149: aligned_free (Memory.h:177)
==20193==    by 0x129149: conditional_aligned_free<true> (Memory.h:230)
==20193==    by 0x129149: conditional_aligned_delete_auto<double, true> (Memory.h:416)
==20193==    by 0x129149: ~DenseStorage (DenseStorage.h:391)
==20193==    by 0x129149: ~PlainObjectBase (PlainObjectBase.h:98)
==20193==    by 0x129149: ~Matrix (Matrix.h:178)
==20193==    by 0x129149: rascal::Hyp1f1GradientProvider::f(Eigen::Matrix<double, 1, 1, 0, 1, 1> const&) (test_math.hh:482)
==20193==    by 0x133EA3: void rascal::test_gradients<rascal::Hyp1f1GradientProvider, rascal::GradientTestFixture>(rascal::Hyp1f1GradientProvider, rascal::GradientTestFixture) (test_math.hh:334)
==20193==    by 0x11D112: rascal::MathHyp1f1Tests::hyp1f1_gradient_test::test_method() (test_math_hyp1f1.cc:141)
==20193==    by 0x11D71C: rascal::MathHyp1f1Tests::hyp1f1_gradient_test_invoker() (test_math_hyp1f1.cc:131)
==20193==    by 0x4E872CD: boost::detail::function::function_obj_invoker0<boost::detail::forward, int>::invoke(boost::detail::function::function_buffer&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E8677C: boost::execution_monitor::catch_signals(boost::function<int ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E86860: boost::execution_monitor::execute(boost::function<int ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E86FDC: boost::execution_monitor::vexecute(boost::function<void ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4EB58D0: boost::unit_test::unit_test_monitor_t::execute_and_translate(boost::function<void ()> const&, unsigned int) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E91C6A: boost::unit_test::framework::state::execute_test_tree(unsigned long, unsigned int, boost::unit_test::framework::state::random_generator_helper const*) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E91E50: boost::unit_test::framework::state::execute_test_tree(unsigned long, unsigned int, boost::unit_test::framework::state::random_generator_helper const*) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==  Block was alloc'd at
==20193==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==20193==    by 0x121F50: aligned_malloc (Memory.h:159)
==20193==    by 0x121F50: conditional_aligned_malloc<true> (Memory.h:214)
==20193==    by 0x121F50: double* Eigen::internal::conditional_aligned_new_auto<double, true>(unsigned long) (Memory.h:374)
==20193==    by 0x123017: resize (DenseStorage.h:408)
==20193==    by 0x123017: Eigen::PlainObjectBase<Eigen::Matrix<double, -1, -1, 0, -1, -1> >::resize(long, long) (PlainObjectBase.h:293)
==20193==    by 0x129095: _init2<long unsigned int, long unsigned int> (PlainObjectBase.h:739)
==20193==    by 0x129095: Matrix<long unsigned int, long unsigned int> (Matrix.h:304)
==20193==    by 0x129095: rascal::Hyp1f1GradientProvider::f(Eigen::Matrix<double, 1, 1, 0, 1, 1> const&) (test_math.hh:482)
==20193==    by 0x133EA3: void rascal::test_gradients<rascal::Hyp1f1GradientProvider, rascal::GradientTestFixture>(rascal::Hyp1f1GradientProvider, rascal::GradientTestFixture) (test_math.hh:334)
==20193==    by 0x11D112: rascal::MathHyp1f1Tests::hyp1f1_gradient_test::test_method() (test_math_hyp1f1.cc:141)
==20193==    by 0x11D71C: rascal::MathHyp1f1Tests::hyp1f1_gradient_test_invoker() (test_math_hyp1f1.cc:131)
==20193==    by 0x4E872CD: boost::detail::function::function_obj_invoker0<boost::detail::forward, int>::invoke(boost::detail::function::function_buffer&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E8677C: boost::execution_monitor::catch_signals(boost::function<int ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E86860: boost::execution_monitor::execute(boost::function<int ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E86FDC: boost::execution_monitor::vexecute(boost::function<void ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4EB58D0: boost::unit_test::unit_test_monitor_t::execute_and_translate(boost::function<void ()> const&, unsigned int) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193== 
==20193== Invalid read of size 8
==20193==    at 0x134D30: assignCoeff (AssignEvaluator.h:631)
==20193==    by 0x134D30: assignCoeffByOuterInner (AssignEvaluator.h:645)
==20193==    by 0x134D30: run (AssignEvaluator.h:326)
==20193==    by 0x134D30: call_dense_assignment_loop<Eigen::Matrix<double, -1, -1>, Eigen::Ref<Eigen::Array<double, 1, -1, 1, 1, -1> >, Eigen::internal::assign_op<double, double> > (AssignEvaluator.h:741)
==20193==    by 0x134D30: run (AssignEvaluator.h:879)
==20193==    by 0x134D30: call_assignment_no_alias<Eigen::Matrix<double, -1, -1>, Eigen::Ref<Eigen::Array<double, 1, -1, 1, 1, -1> >, Eigen::internal::assign_op<double, double> > (AssignEvaluator.h:836)
==20193==    by 0x134D30: _set_noalias<Eigen::Ref<Eigen::Array<double, 1, -1, 1, 1, -1> > > (PlainObjectBase.h:728)
==20193==    by 0x134D30: PlainObjectBase<Eigen::Ref<Eigen::Array<double, 1, -1, 1, 1, -1> > > (PlainObjectBase.h:537)
==20193==    by 0x134D30: Matrix<Eigen::Ref<Eigen::Array<double, 1, -1, 1, 1, -1> > > (Matrix.h:379)
==20193==    by 0x134D30: void rascal::test_gradients<rascal::Hyp1f1GradientProvider, rascal::GradientTestFixture>(rascal::Hyp1f1GradientProvider, rascal::GradientTestFixture) (test_math.hh:335)
==20193==    by 0x11D112: rascal::MathHyp1f1Tests::hyp1f1_gradient_test::test_method() (test_math_hyp1f1.cc:141)
==20193==    by 0x11D71C: rascal::MathHyp1f1Tests::hyp1f1_gradient_test_invoker() (test_math_hyp1f1.cc:131)
==20193==    by 0x4E872CD: boost::detail::function::function_obj_invoker0<boost::detail::forward, int>::invoke(boost::detail::function::function_buffer&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E8677C: boost::execution_monitor::catch_signals(boost::function<int ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E86860: boost::execution_monitor::execute(boost::function<int ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E86FDC: boost::execution_monitor::vexecute(boost::function<void ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4EB58D0: boost::unit_test::unit_test_monitor_t::execute_and_translate(boost::function<void ()> const&, unsigned int) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E91C6A: boost::unit_test::framework::state::execute_test_tree(unsigned long, unsigned int, boost::unit_test::framework::state::random_generator_helper const*) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E91E50: boost::unit_test::framework::state::execute_test_tree(unsigned long, unsigned int, boost::unit_test::framework::state::random_generator_helper const*) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E91E50: boost::unit_test::framework::state::execute_test_tree(unsigned long, unsigned int, boost::unit_test::framework::state::random_generator_helper const*) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E8ACC7: boost::unit_test::framework::run(unsigned long, bool) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==  Address 0x6080080 is 0 bytes inside a block of size 96 free'd
==20193==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==20193==    by 0x134C69: aligned_free (Memory.h:177)
==20193==    by 0x134C69: conditional_aligned_free<true> (Memory.h:230)
==20193==    by 0x134C69: conditional_aligned_delete_auto<double, true> (Memory.h:416)
==20193==    by 0x134C69: ~DenseStorage (DenseStorage.h:391)
==20193==    by 0x134C69: ~PlainObjectBase (PlainObjectBase.h:98)
==20193==    by 0x134C69: ~Matrix (Matrix.h:178)
==20193==    by 0x134C69: grad_f (test_math.hh:492)
==20193==    by 0x134C69: void rascal::test_gradients<rascal::Hyp1f1GradientProvider, rascal::GradientTestFixture>(rascal::Hyp1f1GradientProvider, rascal::GradientTestFixture) (test_math.hh:335)
==20193==    by 0x11D112: rascal::MathHyp1f1Tests::hyp1f1_gradient_test::test_method() (test_math_hyp1f1.cc:141)
==20193==    by 0x11D71C: rascal::MathHyp1f1Tests::hyp1f1_gradient_test_invoker() (test_math_hyp1f1.cc:131)
==20193==    by 0x4E872CD: boost::detail::function::function_obj_invoker0<boost::detail::forward, int>::invoke(boost::detail::function::function_buffer&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E8677C: boost::execution_monitor::catch_signals(boost::function<int ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E86860: boost::execution_monitor::execute(boost::function<int ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E86FDC: boost::execution_monitor::vexecute(boost::function<void ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4EB58D0: boost::unit_test::unit_test_monitor_t::execute_and_translate(boost::function<void ()> const&, unsigned int) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E91C6A: boost::unit_test::framework::state::execute_test_tree(unsigned long, unsigned int, boost::unit_test::framework::state::random_generator_helper const*) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E91E50: boost::unit_test::framework::state::execute_test_tree(unsigned long, unsigned int, boost::unit_test::framework::state::random_generator_helper const*) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E91E50: boost::unit_test::framework::state::execute_test_tree(unsigned long, unsigned int, boost::unit_test::framework::state::random_generator_helper const*) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==  Block was alloc'd at
==20193==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==20193==    by 0x121F50: aligned_malloc (Memory.h:159)
==20193==    by 0x121F50: conditional_aligned_malloc<true> (Memory.h:214)
==20193==    by 0x121F50: double* Eigen::internal::conditional_aligned_new_auto<double, true>(unsigned long) (Memory.h:374)
==20193==    by 0x123017: resize (DenseStorage.h:408)
==20193==    by 0x123017: Eigen::PlainObjectBase<Eigen::Matrix<double, -1, -1, 0, -1, -1> >::resize(long, long) (PlainObjectBase.h:293)
==20193==    by 0x134BAE: _init2<long unsigned int, long unsigned int> (PlainObjectBase.h:739)
==20193==    by 0x134BAE: Matrix<long unsigned int, long unsigned int> (Matrix.h:304)
==20193==    by 0x134BAE: grad_f (test_math.hh:492)
==20193==    by 0x134BAE: void rascal::test_gradients<rascal::Hyp1f1GradientProvider, rascal::GradientTestFixture>(rascal::Hyp1f1GradientProvider, rascal::GradientTestFixture) (test_math.hh:335)
==20193==    by 0x11D112: rascal::MathHyp1f1Tests::hyp1f1_gradient_test::test_method() (test_math_hyp1f1.cc:141)
==20193==    by 0x11D71C: rascal::MathHyp1f1Tests::hyp1f1_gradient_test_invoker() (test_math_hyp1f1.cc:131)
==20193==    by 0x4E872CD: boost::detail::function::function_obj_invoker0<boost::detail::forward, int>::invoke(boost::detail::function::function_buffer&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E8677C: boost::execution_monitor::catch_signals(boost::function<int ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E86860: boost::execution_monitor::execute(boost::function<int ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E86FDC: boost::execution_monitor::vexecute(boost::function<void ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4EB58D0: boost::unit_test::unit_test_monitor_t::execute_and_translate(boost::function<void ()> const&, unsigned int) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E91C6A: boost::unit_test::framework::state::execute_test_tree(unsigned long, unsigned int, boost::unit_test::framework::state::random_generator_helper const*) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193== 
==20193== Invalid read of size 16
==20193==    at 0x135150: _mm_loadu_pd (emmintrin.h:131)
==20193==    by 0x135150: ploadu<__vector(2) double> (PacketMath.h:336)
==20193==    by 0x135150: ploadt<__vector(2) double, 0> (GenericPacketMath.h:465)
==20193==    by 0x135150: packet<0, __vector(2) double> (CoreEvaluators.h:867)
==20193==    by 0x135150: assignPacket<16, 0, __vector(2) double> (AssignEvaluator.h:658)
==20193==    by 0x135150: run (AssignEvaluator.h:416)
==20193==    by 0x135150: call_dense_assignment_loop<Eigen::Transpose<Eigen::Matrix<double, -1, 1> >, Eigen::Ref<Eigen::Array<double, 1, -1, 1, 1, -1> >, Eigen::internal::assign_op<double, double> > (AssignEvaluator.h:741)
==20193==    by 0x135150: run (AssignEvaluator.h:879)
==20193==    by 0x135150: call_assignment_no_alias<Eigen::Matrix<double, -1, 1>, Eigen::Ref<Eigen::Array<double, 1, -1, 1, 1, -1> >, Eigen::internal::assign_op<double, double> > (AssignEvaluator.h:836)
==20193==    by 0x135150: _set_noalias<Eigen::Ref<Eigen::Array<double, 1, -1, 1, 1, -1> > > (PlainObjectBase.h:728)
==20193==    by 0x135150: _init1<Eigen::Ref<Eigen::Array<double, 1, -1, 1, 1, -1> >, Eigen::Ref<Eigen::Array<double, 1, -1, 1, 1, -1> > > (PlainObjectBase.h:812)
==20193==    by 0x135150: Matrix<Eigen::Ref<Eigen::Array<double, 1, -1, 1, 1, -1> > > (Matrix.h:296)
==20193==    by 0x135150: void rascal::test_gradients<rascal::Hyp1f1GradientProvider, rascal::GradientTestFixture>(rascal::Hyp1f1GradientProvider, rascal::GradientTestFixture) (test_math.hh:370)
==20193==    by 0x11D112: rascal::MathHyp1f1Tests::hyp1f1_gradient_test::test_method() (test_math_hyp1f1.cc:141)
==20193==    by 0x11D71C: rascal::MathHyp1f1Tests::hyp1f1_gradient_test_invoker() (test_math_hyp1f1.cc:131)
==20193==    by 0x4E872CD: boost::detail::function::function_obj_invoker0<boost::detail::forward, int>::invoke(boost::detail::function::function_buffer&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E8677C: boost::execution_monitor::catch_signals(boost::function<int ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E86860: boost::execution_monitor::execute(boost::function<int ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E86FDC: boost::execution_monitor::vexecute(boost::function<void ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4EB58D0: boost::unit_test::unit_test_monitor_t::execute_and_translate(boost::function<void ()> const&, unsigned int) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E91C6A: boost::unit_test::framework::state::execute_test_tree(unsigned long, unsigned int, boost::unit_test::framework::state::random_generator_helper const*) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E91E50: boost::unit_test::framework::state::execute_test_tree(unsigned long, unsigned int, boost::unit_test::framework::state::random_generator_helper const*) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E91E50: boost::unit_test::framework::state::execute_test_tree(unsigned long, unsigned int, boost::unit_test::framework::state::random_generator_helper const*) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E8ACC7: boost::unit_test::framework::run(unsigned long, bool) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==  Address 0x95fd5f0 is 0 bytes inside a block of size 96 free'd
==20193==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==20193==    by 0x129149: aligned_free (Memory.h:177)
==20193==    by 0x129149: conditional_aligned_free<true> (Memory.h:230)
==20193==    by 0x129149: conditional_aligned_delete_auto<double, true> (Memory.h:416)
==20193==    by 0x129149: ~DenseStorage (DenseStorage.h:391)
==20193==    by 0x129149: ~PlainObjectBase (PlainObjectBase.h:98)
==20193==    by 0x129149: ~Matrix (Matrix.h:178)
==20193==    by 0x129149: rascal::Hyp1f1GradientProvider::f(Eigen::Matrix<double, 1, 1, 0, 1, 1> const&) (test_math.hh:482)
==20193==    by 0x1350D7: void rascal::test_gradients<rascal::Hyp1f1GradientProvider, rascal::GradientTestFixture>(rascal::Hyp1f1GradientProvider, rascal::GradientTestFixture) (test_math.hh:370)
==20193==    by 0x11D112: rascal::MathHyp1f1Tests::hyp1f1_gradient_test::test_method() (test_math_hyp1f1.cc:141)
==20193==    by 0x11D71C: rascal::MathHyp1f1Tests::hyp1f1_gradient_test_invoker() (test_math_hyp1f1.cc:131)
==20193==    by 0x4E872CD: boost::detail::function::function_obj_invoker0<boost::detail::forward, int>::invoke(boost::detail::function::function_buffer&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E8677C: boost::execution_monitor::catch_signals(boost::function<int ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E86860: boost::execution_monitor::execute(boost::function<int ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E86FDC: boost::execution_monitor::vexecute(boost::function<void ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4EB58D0: boost::unit_test::unit_test_monitor_t::execute_and_translate(boost::function<void ()> const&, unsigned int) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E91C6A: boost::unit_test::framework::state::execute_test_tree(unsigned long, unsigned int, boost::unit_test::framework::state::random_generator_helper const*) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E91E50: boost::unit_test::framework::state::execute_test_tree(unsigned long, unsigned int, boost::unit_test::framework::state::random_generator_helper const*) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==  Block was alloc'd at
==20193==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==20193==    by 0x121F50: aligned_malloc (Memory.h:159)
==20193==    by 0x121F50: conditional_aligned_malloc<true> (Memory.h:214)
==20193==    by 0x121F50: double* Eigen::internal::conditional_aligned_new_auto<double, true>(unsigned long) (Memory.h:374)
==20193==    by 0x123017: resize (DenseStorage.h:408)
==20193==    by 0x123017: Eigen::PlainObjectBase<Eigen::Matrix<double, -1, -1, 0, -1, -1> >::resize(long, long) (PlainObjectBase.h:293)
==20193==    by 0x129095: _init2<long unsigned int, long unsigned int> (PlainObjectBase.h:739)
==20193==    by 0x129095: Matrix<long unsigned int, long unsigned int> (Matrix.h:304)
==20193==    by 0x129095: rascal::Hyp1f1GradientProvider::f(Eigen::Matrix<double, 1, 1, 0, 1, 1> const&) (test_math.hh:482)
==20193==    by 0x1350D7: void rascal::test_gradients<rascal::Hyp1f1GradientProvider, rascal::GradientTestFixture>(rascal::Hyp1f1GradientProvider, rascal::GradientTestFixture) (test_math.hh:370)
==20193==    by 0x11D112: rascal::MathHyp1f1Tests::hyp1f1_gradient_test::test_method() (test_math_hyp1f1.cc:141)
==20193==    by 0x11D71C: rascal::MathHyp1f1Tests::hyp1f1_gradient_test_invoker() (test_math_hyp1f1.cc:131)
==20193==    by 0x4E872CD: boost::detail::function::function_obj_invoker0<boost::detail::forward, int>::invoke(boost::detail::function::function_buffer&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E8677C: boost::execution_monitor::catch_signals(boost::function<int ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E86860: boost::execution_monitor::execute(boost::function<int ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E86FDC: boost::execution_monitor::vexecute(boost::function<void ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4EB58D0: boost::unit_test::unit_test_monitor_t::execute_and_translate(boost::function<void ()> const&, unsigned int) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193== 
==20193== Invalid read of size 16
==20193==    at 0x135160: run (AssignEvaluator.h:415)
==20193==    by 0x135160: call_dense_assignment_loop<Eigen::Transpose<Eigen::Matrix<double, -1, 1> >, Eigen::Ref<Eigen::Array<double, 1, -1, 1, 1, -1> >, Eigen::internal::assign_op<double, double> > (AssignEvaluator.h:741)
==20193==    by 0x135160: run (AssignEvaluator.h:879)
==20193==    by 0x135160: call_assignment_no_alias<Eigen::Matrix<double, -1, 1>, Eigen::Ref<Eigen::Array<double, 1, -1, 1, 1, -1> >, Eigen::internal::assign_op<double, double> > (AssignEvaluator.h:836)
==20193==    by 0x135160: _set_noalias<Eigen::Ref<Eigen::Array<double, 1, -1, 1, 1, -1> > > (PlainObjectBase.h:728)
==20193==    by 0x135160: _init1<Eigen::Ref<Eigen::Array<double, 1, -1, 1, 1, -1> >, Eigen::Ref<Eigen::Array<double, 1, -1, 1, 1, -1> > > (PlainObjectBase.h:812)
==20193==    by 0x135160: Matrix<Eigen::Ref<Eigen::Array<double, 1, -1, 1, 1, -1> > > (Matrix.h:296)
==20193==    by 0x135160: void rascal::test_gradients<rascal::Hyp1f1GradientProvider, rascal::GradientTestFixture>(rascal::Hyp1f1GradientProvider, rascal::GradientTestFixture) (test_math.hh:370)
==20193==    by 0x11D112: rascal::MathHyp1f1Tests::hyp1f1_gradient_test::test_method() (test_math_hyp1f1.cc:141)
==20193==    by 0x11D71C: rascal::MathHyp1f1Tests::hyp1f1_gradient_test_invoker() (test_math_hyp1f1.cc:131)
==20193==    by 0x4E872CD: boost::detail::function::function_obj_invoker0<boost::detail::forward, int>::invoke(boost::detail::function::function_buffer&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E8677C: boost::execution_monitor::catch_signals(boost::function<int ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E86860: boost::execution_monitor::execute(boost::function<int ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E86FDC: boost::execution_monitor::vexecute(boost::function<void ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4EB58D0: boost::unit_test::unit_test_monitor_t::execute_and_translate(boost::function<void ()> const&, unsigned int) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E91C6A: boost::unit_test::framework::state::execute_test_tree(unsigned long, unsigned int, boost::unit_test::framework::state::random_generator_helper const*) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E91E50: boost::unit_test::framework::state::execute_test_tree(unsigned long, unsigned int, boost::unit_test::framework::state::random_generator_helper const*) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E91E50: boost::unit_test::framework::state::execute_test_tree(unsigned long, unsigned int, boost::unit_test::framework::state::random_generator_helper const*) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E8ACC7: boost::unit_test::framework::run(unsigned long, bool) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==  Address 0x95fd610 is 32 bytes inside a block of size 96 free'd
==20193==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==20193==    by 0x129149: aligned_free (Memory.h:177)
==20193==    by 0x129149: conditional_aligned_free<true> (Memory.h:230)
==20193==    by 0x129149: conditional_aligned_delete_auto<double, true> (Memory.h:416)
==20193==    by 0x129149: ~DenseStorage (DenseStorage.h:391)
==20193==    by 0x129149: ~PlainObjectBase (PlainObjectBase.h:98)
==20193==    by 0x129149: ~Matrix (Matrix.h:178)
==20193==    by 0x129149: rascal::Hyp1f1GradientProvider::f(Eigen::Matrix<double, 1, 1, 0, 1, 1> const&) (test_math.hh:482)
==20193==    by 0x1350D7: void rascal::test_gradients<rascal::Hyp1f1GradientProvider, rascal::GradientTestFixture>(rascal::Hyp1f1GradientProvider, rascal::GradientTestFixture) (test_math.hh:370)
==20193==    by 0x11D112: rascal::MathHyp1f1Tests::hyp1f1_gradient_test::test_method() (test_math_hyp1f1.cc:141)
==20193==    by 0x11D71C: rascal::MathHyp1f1Tests::hyp1f1_gradient_test_invoker() (test_math_hyp1f1.cc:131)
==20193==    by 0x4E872CD: boost::detail::function::function_obj_invoker0<boost::detail::forward, int>::invoke(boost::detail::function::function_buffer&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E8677C: boost::execution_monitor::catch_signals(boost::function<int ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E86860: boost::execution_monitor::execute(boost::function<int ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E86FDC: boost::execution_monitor::vexecute(boost::function<void ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4EB58D0: boost::unit_test::unit_test_monitor_t::execute_and_translate(boost::function<void ()> const&, unsigned int) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E91C6A: boost::unit_test::framework::state::execute_test_tree(unsigned long, unsigned int, boost::unit_test::framework::state::random_generator_helper const*) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E91E50: boost::unit_test::framework::state::execute_test_tree(unsigned long, unsigned int, boost::unit_test::framework::state::random_generator_helper const*) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==  Block was alloc'd at
==20193==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==20193==    by 0x121F50: aligned_malloc (Memory.h:159)
==20193==    by 0x121F50: conditional_aligned_malloc<true> (Memory.h:214)
==20193==    by 0x121F50: double* Eigen::internal::conditional_aligned_new_auto<double, true>(unsigned long) (Memory.h:374)
==20193==    by 0x123017: resize (DenseStorage.h:408)
==20193==    by 0x123017: Eigen::PlainObjectBase<Eigen::Matrix<double, -1, -1, 0, -1, -1> >::resize(long, long) (PlainObjectBase.h:293)
==20193==    by 0x129095: _init2<long unsigned int, long unsigned int> (PlainObjectBase.h:739)
==20193==    by 0x129095: Matrix<long unsigned int, long unsigned int> (Matrix.h:304)
==20193==    by 0x129095: rascal::Hyp1f1GradientProvider::f(Eigen::Matrix<double, 1, 1, 0, 1, 1> const&) (test_math.hh:482)
==20193==    by 0x1350D7: void rascal::test_gradients<rascal::Hyp1f1GradientProvider, rascal::GradientTestFixture>(rascal::Hyp1f1GradientProvider, rascal::GradientTestFixture) (test_math.hh:370)
==20193==    by 0x11D112: rascal::MathHyp1f1Tests::hyp1f1_gradient_test::test_method() (test_math_hyp1f1.cc:141)
==20193==    by 0x11D71C: rascal::MathHyp1f1Tests::hyp1f1_gradient_test_invoker() (test_math_hyp1f1.cc:131)
==20193==    by 0x4E872CD: boost::detail::function::function_obj_invoker0<boost::detail::forward, int>::invoke(boost::detail::function::function_buffer&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E8677C: boost::execution_monitor::catch_signals(boost::function<int ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E86860: boost::execution_monitor::execute(boost::function<int ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E86FDC: boost::execution_monitor::vexecute(boost::function<void ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4EB58D0: boost::unit_test::unit_test_monitor_t::execute_and_translate(boost::function<void ()> const&, unsigned int) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193== 
==20193== Invalid read of size 16
==20193==    at 0x135238: _mm_loadu_pd (emmintrin.h:131)
==20193==    by 0x135238: ploadu<__vector(2) double> (PacketMath.h:336)
==20193==    by 0x135238: ploadt<__vector(2) double, 0> (GenericPacketMath.h:465)
==20193==    by 0x135238: packet<0, __vector(2) double> (CoreEvaluators.h:867)
==20193==    by 0x135238: assignPacket<16, 0, __vector(2) double> (AssignEvaluator.h:658)
==20193==    by 0x135238: run (AssignEvaluator.h:416)
==20193==    by 0x135238: call_dense_assignment_loop<Eigen::Transpose<Eigen::Matrix<double, -1, 1> >, Eigen::Ref<Eigen::Array<double, 1, -1, 1, 1, -1> >, Eigen::internal::assign_op<double, double> > (AssignEvaluator.h:741)
==20193==    by 0x135238: run (AssignEvaluator.h:879)
==20193==    by 0x135238: call_assignment_no_alias<Eigen::Matrix<double, -1, 1>, Eigen::Ref<Eigen::Array<double, 1, -1, 1, 1, -1> >, Eigen::internal::assign_op<double, double> > (AssignEvaluator.h:836)
==20193==    by 0x135238: _set_noalias<Eigen::Ref<Eigen::Array<double, 1, -1, 1, 1, -1> > > (PlainObjectBase.h:728)
==20193==    by 0x135238: _init1<Eigen::Ref<Eigen::Array<double, 1, -1, 1, 1, -1> >, Eigen::Ref<Eigen::Array<double, 1, -1, 1, 1, -1> > > (PlainObjectBase.h:812)
==20193==    by 0x135238: Matrix<Eigen::Ref<Eigen::Array<double, 1, -1, 1, 1, -1> > > (Matrix.h:296)
==20193==    by 0x135238: void rascal::test_gradients<rascal::Hyp1f1GradientProvider, rascal::GradientTestFixture>(rascal::Hyp1f1GradientProvider, rascal::GradientTestFixture) (test_math.hh:372)
==20193==    by 0x11D112: rascal::MathHyp1f1Tests::hyp1f1_gradient_test::test_method() (test_math_hyp1f1.cc:141)
==20193==    by 0x11D71C: rascal::MathHyp1f1Tests::hyp1f1_gradient_test_invoker() (test_math_hyp1f1.cc:131)
==20193==    by 0x4E872CD: boost::detail::function::function_obj_invoker0<boost::detail::forward, int>::invoke(boost::detail::function::function_buffer&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E8677C: boost::execution_monitor::catch_signals(boost::function<int ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E86860: boost::execution_monitor::execute(boost::function<int ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E86FDC: boost::execution_monitor::vexecute(boost::function<void ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4EB58D0: boost::unit_test::unit_test_monitor_t::execute_and_translate(boost::function<void ()> const&, unsigned int) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E91C6A: boost::unit_test::framework::state::execute_test_tree(unsigned long, unsigned int, boost::unit_test::framework::state::random_generator_helper const*) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E91E50: boost::unit_test::framework::state::execute_test_tree(unsigned long, unsigned int, boost::unit_test::framework::state::random_generator_helper const*) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E91E50: boost::unit_test::framework::state::execute_test_tree(unsigned long, unsigned int, boost::unit_test::framework::state::random_generator_helper const*) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E8ACC7: boost::unit_test::framework::run(unsigned long, bool) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==  Address 0x96dd960 is 0 bytes inside a block of size 96 free'd
==20193==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==20193==    by 0x129149: aligned_free (Memory.h:177)
==20193==    by 0x129149: conditional_aligned_free<true> (Memory.h:230)
==20193==    by 0x129149: conditional_aligned_delete_auto<double, true> (Memory.h:416)
==20193==    by 0x129149: ~DenseStorage (DenseStorage.h:391)
==20193==    by 0x129149: ~PlainObjectBase (PlainObjectBase.h:98)
==20193==    by 0x129149: ~Matrix (Matrix.h:178)
==20193==    by 0x129149: rascal::Hyp1f1GradientProvider::f(Eigen::Matrix<double, 1, 1, 0, 1, 1> const&) (test_math.hh:482)
==20193==    by 0x1351B4: void rascal::test_gradients<rascal::Hyp1f1GradientProvider, rascal::GradientTestFixture>(rascal::Hyp1f1GradientProvider, rascal::GradientTestFixture) (test_math.hh:372)
==20193==    by 0x11D112: rascal::MathHyp1f1Tests::hyp1f1_gradient_test::test_method() (test_math_hyp1f1.cc:141)
==20193==    by 0x11D71C: rascal::MathHyp1f1Tests::hyp1f1_gradient_test_invoker() (test_math_hyp1f1.cc:131)
==20193==    by 0x4E872CD: boost::detail::function::function_obj_invoker0<boost::detail::forward, int>::invoke(boost::detail::function::function_buffer&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E8677C: boost::execution_monitor::catch_signals(boost::function<int ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E86860: boost::execution_monitor::execute(boost::function<int ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E86FDC: boost::execution_monitor::vexecute(boost::function<void ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4EB58D0: boost::unit_test::unit_test_monitor_t::execute_and_translate(boost::function<void ()> const&, unsigned int) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E91C6A: boost::unit_test::framework::state::execute_test_tree(unsigned long, unsigned int, boost::unit_test::framework::state::random_generator_helper const*) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E91E50: boost::unit_test::framework::state::execute_test_tree(unsigned long, unsigned int, boost::unit_test::framework::state::random_generator_helper const*) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==  Block was alloc'd at
==20193==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==20193==    by 0x121F50: aligned_malloc (Memory.h:159)
==20193==    by 0x121F50: conditional_aligned_malloc<true> (Memory.h:214)
==20193==    by 0x121F50: double* Eigen::internal::conditional_aligned_new_auto<double, true>(unsigned long) (Memory.h:374)
==20193==    by 0x123017: resize (DenseStorage.h:408)
==20193==    by 0x123017: Eigen::PlainObjectBase<Eigen::Matrix<double, -1, -1, 0, -1, -1> >::resize(long, long) (PlainObjectBase.h:293)
==20193==    by 0x129095: _init2<long unsigned int, long unsigned int> (PlainObjectBase.h:739)
==20193==    by 0x129095: Matrix<long unsigned int, long unsigned int> (Matrix.h:304)
==20193==    by 0x129095: rascal::Hyp1f1GradientProvider::f(Eigen::Matrix<double, 1, 1, 0, 1, 1> const&) (test_math.hh:482)
==20193==    by 0x1351B4: void rascal::test_gradients<rascal::Hyp1f1GradientProvider, rascal::GradientTestFixture>(rascal::Hyp1f1GradientProvider, rascal::GradientTestFixture) (test_math.hh:372)
==20193==    by 0x11D112: rascal::MathHyp1f1Tests::hyp1f1_gradient_test::test_method() (test_math_hyp1f1.cc:141)
==20193==    by 0x11D71C: rascal::MathHyp1f1Tests::hyp1f1_gradient_test_invoker() (test_math_hyp1f1.cc:131)
==20193==    by 0x4E872CD: boost::detail::function::function_obj_invoker0<boost::detail::forward, int>::invoke(boost::detail::function::function_buffer&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E8677C: boost::execution_monitor::catch_signals(boost::function<int ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E86860: boost::execution_monitor::execute(boost::function<int ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E86FDC: boost::execution_monitor::vexecute(boost::function<void ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4EB58D0: boost::unit_test::unit_test_monitor_t::execute_and_translate(boost::function<void ()> const&, unsigned int) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193== 
==20193== Invalid read of size 16
==20193==    at 0x135249: run (AssignEvaluator.h:415)
==20193==    by 0x135249: call_dense_assignment_loop<Eigen::Transpose<Eigen::Matrix<double, -1, 1> >, Eigen::Ref<Eigen::Array<double, 1, -1, 1, 1, -1> >, Eigen::internal::assign_op<double, double> > (AssignEvaluator.h:741)
==20193==    by 0x135249: run (AssignEvaluator.h:879)
==20193==    by 0x135249: call_assignment_no_alias<Eigen::Matrix<double, -1, 1>, Eigen::Ref<Eigen::Array<double, 1, -1, 1, 1, -1> >, Eigen::internal::assign_op<double, double> > (AssignEvaluator.h:836)
==20193==    by 0x135249: _set_noalias<Eigen::Ref<Eigen::Array<double, 1, -1, 1, 1, -1> > > (PlainObjectBase.h:728)
==20193==    by 0x135249: _init1<Eigen::Ref<Eigen::Array<double, 1, -1, 1, 1, -1> >, Eigen::Ref<Eigen::Array<double, 1, -1, 1, 1, -1> > > (PlainObjectBase.h:812)
==20193==    by 0x135249: Matrix<Eigen::Ref<Eigen::Array<double, 1, -1, 1, 1, -1> > > (Matrix.h:296)
==20193==    by 0x135249: void rascal::test_gradients<rascal::Hyp1f1GradientProvider, rascal::GradientTestFixture>(rascal::Hyp1f1GradientProvider, rascal::GradientTestFixture) (test_math.hh:372)
==20193==    by 0x11D112: rascal::MathHyp1f1Tests::hyp1f1_gradient_test::test_method() (test_math_hyp1f1.cc:141)
==20193==    by 0x11D71C: rascal::MathHyp1f1Tests::hyp1f1_gradient_test_invoker() (test_math_hyp1f1.cc:131)
==20193==    by 0x4E872CD: boost::detail::function::function_obj_invoker0<boost::detail::forward, int>::invoke(boost::detail::function::function_buffer&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E8677C: boost::execution_monitor::catch_signals(boost::function<int ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E86860: boost::execution_monitor::execute(boost::function<int ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E86FDC: boost::execution_monitor::vexecute(boost::function<void ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4EB58D0: boost::unit_test::unit_test_monitor_t::execute_and_translate(boost::function<void ()> const&, unsigned int) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E91C6A: boost::unit_test::framework::state::execute_test_tree(unsigned long, unsigned int, boost::unit_test::framework::state::random_generator_helper const*) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E91E50: boost::unit_test::framework::state::execute_test_tree(unsigned long, unsigned int, boost::unit_test::framework::state::random_generator_helper const*) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E91E50: boost::unit_test::framework::state::execute_test_tree(unsigned long, unsigned int, boost::unit_test::framework::state::random_generator_helper const*) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E8ACC7: boost::unit_test::framework::run(unsigned long, bool) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==  Address 0x96dd980 is 32 bytes inside a block of size 96 free'd
==20193==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==20193==    by 0x129149: aligned_free (Memory.h:177)
==20193==    by 0x129149: conditional_aligned_free<true> (Memory.h:230)
==20193==    by 0x129149: conditional_aligned_delete_auto<double, true> (Memory.h:416)
==20193==    by 0x129149: ~DenseStorage (DenseStorage.h:391)
==20193==    by 0x129149: ~PlainObjectBase (PlainObjectBase.h:98)
==20193==    by 0x129149: ~Matrix (Matrix.h:178)
==20193==    by 0x129149: rascal::Hyp1f1GradientProvider::f(Eigen::Matrix<double, 1, 1, 0, 1, 1> const&) (test_math.hh:482)
==20193==    by 0x1351B4: void rascal::test_gradients<rascal::Hyp1f1GradientProvider, rascal::GradientTestFixture>(rascal::Hyp1f1GradientProvider, rascal::GradientTestFixture) (test_math.hh:372)
==20193==    by 0x11D112: rascal::MathHyp1f1Tests::hyp1f1_gradient_test::test_method() (test_math_hyp1f1.cc:141)
==20193==    by 0x11D71C: rascal::MathHyp1f1Tests::hyp1f1_gradient_test_invoker() (test_math_hyp1f1.cc:131)
==20193==    by 0x4E872CD: boost::detail::function::function_obj_invoker0<boost::detail::forward, int>::invoke(boost::detail::function::function_buffer&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E8677C: boost::execution_monitor::catch_signals(boost::function<int ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E86860: boost::execution_monitor::execute(boost::function<int ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E86FDC: boost::execution_monitor::vexecute(boost::function<void ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4EB58D0: boost::unit_test::unit_test_monitor_t::execute_and_translate(boost::function<void ()> const&, unsigned int) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E91C6A: boost::unit_test::framework::state::execute_test_tree(unsigned long, unsigned int, boost::unit_test::framework::state::random_generator_helper const*) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E91E50: boost::unit_test::framework::state::execute_test_tree(unsigned long, unsigned int, boost::unit_test::framework::state::random_generator_helper const*) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==  Block was alloc'd at
==20193==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==20193==    by 0x121F50: aligned_malloc (Memory.h:159)
==20193==    by 0x121F50: conditional_aligned_malloc<true> (Memory.h:214)
==20193==    by 0x121F50: double* Eigen::internal::conditional_aligned_new_auto<double, true>(unsigned long) (Memory.h:374)
==20193==    by 0x123017: resize (DenseStorage.h:408)
==20193==    by 0x123017: Eigen::PlainObjectBase<Eigen::Matrix<double, -1, -1, 0, -1, -1> >::resize(long, long) (PlainObjectBase.h:293)
==20193==    by 0x129095: _init2<long unsigned int, long unsigned int> (PlainObjectBase.h:739)
==20193==    by 0x129095: Matrix<long unsigned int, long unsigned int> (Matrix.h:304)
==20193==    by 0x129095: rascal::Hyp1f1GradientProvider::f(Eigen::Matrix<double, 1, 1, 0, 1, 1> const&) (test_math.hh:482)
==20193==    by 0x1351B4: void rascal::test_gradients<rascal::Hyp1f1GradientProvider, rascal::GradientTestFixture>(rascal::Hyp1f1GradientProvider, rascal::GradientTestFixture) (test_math.hh:372)
==20193==    by 0x11D112: rascal::MathHyp1f1Tests::hyp1f1_gradient_test::test_method() (test_math_hyp1f1.cc:141)
==20193==    by 0x11D71C: rascal::MathHyp1f1Tests::hyp1f1_gradient_test_invoker() (test_math_hyp1f1.cc:131)
==20193==    by 0x4E872CD: boost::detail::function::function_obj_invoker0<boost::detail::forward, int>::invoke(boost::detail::function::function_buffer&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E8677C: boost::execution_monitor::catch_signals(boost::function<int ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E86860: boost::execution_monitor::execute(boost::function<int ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4E86FDC: boost::execution_monitor::vexecute(boost::function<void ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193==    by 0x4EB58D0: boost::unit_test::unit_test_monitor_t::execute_and_translate(boost::function<void ()> const&, unsigned int) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==20193== 

*** No errors detected
==20193== 
==20193== HEAP SUMMARY:
==20193==     in use at exit: 0 bytes in 0 blocks
==20193==   total heap usage: 119,422 allocs, 119,422 frees, 104,596,390 bytes allocated
==20193== 
==20193== All heap blocks were freed -- no leaks are possible
==20193== 
==20193== For counts of detected and suppressed errors, rerun with: -v
==20193== ERROR SUMMARY: 660 errors from 6 contexts (suppressed: 0 from 0)
```

<details />

### PR DESCRIPTION
**Pull request by max-veit**
Fix #137 

The problem was that the `Hyp1f1GradientProvider` was returning `Eigen::Ref`s to arrays it didn't actually have persistent storage for. While it worked, it can certainly be considered quite dodgy, so it's right that `valgrind` picked it up.

Tasks before review:

- [x] Add tests, examples, and complete documentation of any added functionality
    - [x] For bugfix pull requests, list here which tests have been added or re-enabled
          to verify the fix and catch future regressions as well as similar bugs
          elsewhere in the code.
        - When the `valgrind` tests are enabled by default (as discussed in #207), this will no longer be an issue.
- [x] Run `make lint` on the project, ensure it passes
    - [x] Run `make pretty-cpp` and `make pretty-python`, check that the
          auto-formatting is sensible
- [x] Merge with master and resolve any conflicts

### CODE REVIEW

File: tests/test_math.hh [hunk 1]
```diff
@@ -484,7 +484,7 @@ namespace rascal {
 
     ~Hyp1f1GradientProvider() = default;
 
-    Eigen::Ref<Eigen::Array<double, 1, Eigen::Dynamic>>
+    Eigen::Array<double, 1, Eigen::Dynamic>
```
Comment (Luthaf) [inline tests/test_math.hh]: So `result_flat` is initialized as an `Eigen::Map<Eigen::Array>`, and then converted to a `Eigen::Array` when returning. Does this creates a copy of the data? If so, why not return a `MatrixXd` instead, or change the code to use `Eigen::Array` everywhere?

File: tests/test_math.hh [hunk 2]
```diff
@@ -481,7 +483,7 @@ namespace rascal {
...
     f(const Eigen::Matrix<double, 1, 1> & input_v) {
       this->hyp1f1_calculator.calc(input_v(0), this->fac_a, this->fac_b);
       Eigen::MatrixXd result(this->max_radial, this->max_angular + 1);
```
Comment (Luthaf) [inline tests/test_math.hh]: This and the next line are making a copy of the data stored inside `this->hyp1f1_calculator`, right? The memory error was that the `Eigen::Ref` was referring to memory allocated by `result`, and freed as `result` got out of scope
at the end of this function.

Could we not make this copy, and instead return a `Eigen::Ref<...>(this->hyp1f1_calculator.get_data())` directly?

File: tests/test_math.hh (hunk 1 above)
Comment (max-veit) [reply tests/test_math.hh]: Not as far as I can tell; the `Map` is just for reshaping the matrix (flattening, as the variable name would suggest) from the original shape of `n_max` by `l_max + 1` (rectangular) to the flat vector that the gradient test expects. The copy on return _should_ be optimized out via RVO into the corresponding vector in `test_gradients`: Either this
https://github.com/cosmo-epfl/librascal/blob/d9dd3e8721eddc8b014e95bcb2340d1e6134acb6/tests/test_math.hh#L340
or one of these
https://github.com/cosmo-epfl/librascal/blob/d9dd3e8721eddc8b014e95bcb2340d1e6134acb6/tests/test_math.hh#L376-L379

So there is _one_ copy that happens, from the Hyp1f1 result array into the local variable of `test_gradients`. But if you look at the gradient testing code you'll see why it's necessary to have that one copy: We need to call `f()` with different input values and compare the results (for a finite-difference analysis). But if `f()` just returns some sort of reference or map to the underlying data in `hyp1f1` then we get big problems because the underlying data changes with each call.

If your question was instead about `Matrix` versus `Array`, then no, there's no copying that happens when converting from one to the other; they're just different interfaces to the same data. Eigen will be able to tell the compiler to optimize out most of the "stupid copies"; better to have clearer expressions that better communicate our intent than horrific un-debuggable errors later on.

File: tests/test_math.hh (hunk 2 above)
Comment (max-veit) [reply tests/test_math.hh]: Please, you're making my head hurt. This is not only a bad idea (see previous comment about aliasing issues) but it's also way overkill for the simple fix that this is. For perspective: This is (a) testing code that's (b) run on only one function that (c) only copies a small amount of data for each iteration of the gradient test that (d) takes a small proportion of the testing time anyway. Let's let Eigen and the compiler worry about superfluous copies; we need to worry more about the correctness of our code.

Comment (Luthaf) [reply tests/test_math.hh]: yeah, sorry I went a bit into overdrive here, I did not realize this was test only code =)
